<a href="https://colab.research.google.com/github/22331A0566/java/blob/main/22331A0566.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

WEEK-1

1. Create a list of five elements. Pass the list to a function and compute the average of
five numbers.

In [ ]:
def average(numbers):
  return sum(numbers)/len(numbers)
numbers = [10,20,30,40,50]
average = average(numbers)
print(f"The average of the numbers is : {average}")

The average of the numbers is : 30.0


2. Write a program that prompts a user to enter the element of a list and add the element
to a list. Write a function maximum(Lst) and minimum(Lst) to find the maximum and
minimum number from the list.

In [ ]:
n = int(input("Enter no.of Elements :- "))
listt = []
for i in range (n):
  i = int(input("Enter the number :- "))
  listt.append(i)

def maximum(l):
  print("Maximum of given list :- ",max(l))

def minimum(l):
  print("Minimum of given list :- ",min(l))

maximum(listt)
minimum(listt)


Enter no.of Elements :- 4
Enter the number :- 2
Enter the number :- 6
Enter the number :- 8
Enter the number :- 9
Maximum of given list :-  9
Minimum of given list :-  2


3. Write a function print_reverse(Lst) to reverse the elements of a list.

In [ ]:
def reverse(list):
  reversed_list = []
  for i in range(len(list) - 1, -1, -1):
    reversed_list.append(list[i])
  return reversed_list
my_list = [1, 2, 3, 4, 5]
reversed_list = reverse(my_list)
print(reversed_list)

[5, 4, 3, 2, 1]


4. Write a program to return prime numbers from a list.

In [ ]:
def is_prime(n):
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True
def get_prime_numbers(list1):
  prime_numbers = []
  for num in list1:
    if is_prime(num):
      prime_numbers.append(num)
  return prime_numbers
list1 = [2, 3, 4, 5, 6, 7, 8, 9, 10]
prime_numbers = get_prime_numbers(list1)
print(prime_numbers)

[2, 3, 5, 7]


WEEK-2

1. Implementing Breadth First Search using python

In [ ]:
from collections import deque
def bfs(graph, start):
    visited = []
    queue = deque([start])
    while queue:
        node = queue.popleft()
        if node not in visited:
            visited.append(node)
            neighbors = graph[node]
            for neighbor in neighbors:
                if neighbor not in visited:
                    queue.append(neighbor)
    return visited
graph = {
    '1': ['2', '3'],
    '2': [ '4', '5'],
    '3': ['6'],
    '4': [],
    '5': ['6'],
    '6': []
}

print(bfs(graph, '3'))

['3', '6']


2. Implementing Depth First Search using python

In [ ]:
def dfs(graph, start):
  visited = set()
  stack = [start]

  while stack:
    node = stack.pop()
    if node not in visited:
      print(node, end=" ")
      visited.add(node)

      for neighbor in graph[node]:
        stack.append(neighbor)

graph = {
  'A': ['B', 'C'],
  'B': ['D', 'E'],
  'C': ['F'],
  'D': [],
  'E': ['F'],
  'F': []
}

dfs(graph, 'A')

A C F B E D 

3. Implementing Depth Limited search using python.

In [ ]:

from collections import deque
def bfs(graph, start):
    visited = []
    queue = deque([start])
    while queue:
        node = queue.popleft()
        if node not in visited:
            visited.append(node)
            neighbors = graph[node]
            for neighbor in neighbors:
                if neighbor not in visited:
                    queue.append(neighbor)
    return visited
graph = {
    '1': ['2', '3'],
    '2': [ '4', '5'],
    '3': ['6'],
    '4': [],
    '5': ['6'],
    '6': []
}

print(bfs(graph, '2'))

['2', '4', '5', '6']


WEEK-3

1. Implementing Best First Search using python.

2. Write a program to Perform operations of NumPy in python -type -length – ndim-
shape -reshape -arange -item size -dtype

In [ ]:
import numpy as np

def numpy_operations_example():
    # Create a numpy array
    arr = np.array([[1, 2, 3], [4, 5, 6]])

    # Type of array
    print("Type of array:")
    print(type(arr))

    # Length of array
    print("\nLength of array:")
    print(len(arr))

    # Number of dimensions (ndim)
    print("\nNumber of dimensions:")
    print(arr.ndim)

    # Shape of array
    print("\nShape of array:")
    print(arr.shape)

    # Reshape array
    print("\nReshaped array:")
    arr_reshaped = np.reshape(arr, (3, 2))
    print(arr_reshaped)

    # Generate array using arange
    print("\nArray using arange:")
    arr_arange = np.arange(0, 10, 2)
    print(arr_arange)

    # Item size of array elements
    print("\nItem size of array elements:")
    print(arr.itemsize)

    # Data type of array
    print("\nData type of array:")
    print(arr.dtype)

if __name__ == "__main__":
    numpy_operations_example()


Type of array:
<class 'numpy.ndarray'>

Length of array:
2

Number of dimensions:
2

Shape of array:
(2, 3)

Reshaped array:
[[1 2]
 [3 4]
 [5 6]]

Array using arange:
[0 2 4 6 8]

Item size of array elements:
8

Data type of array:
int64


3. Write a program in python to perform NumPy arithmetic operations. -add -subtract -
multiply -divide -dot -sin, cos, tan -sum -transpose –power.

In [ ]:
import numpy as np

# Create sample arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
addition = np.add(A, B)
print("Addition:")
print(addition)

# Subtraction
subtraction = np.subtract(A, B)
print("\nSubtraction:")
print(subtraction)

# Multiplication (element-wise)
multiplication = np.multiply(A, B)
print("\nMultiplication:")
print(multiplication)

# Division (element-wise)
division = np.divide(A, B)
print("\nDivision:")
print(division)

# Dot product
dot_product = np.dot(A, B)
print("\nDot Product:")
print(dot_product)

# Trigonometric functions (sin, cos, tan)
print("\nTrigonometric functions:")
sin_A = np.sin(A)
cos_A = np.cos(A)
tan_A = np.tan(A)
print("sin(A):\n", sin_A)
print("cos(A):\n", cos_A)
print("tan(A):\n", tan_A)

# Sum of all elements
sum_A = np.sum(A)
print("\nSum of all elements in A:", sum_A)

# Transpose of an array
transpose_A = np.transpose(A)
print("\nTranspose of A:")
print(transpose_A)

# Power operation
power_A = np.power(A, 2)  # Square of each element
print("\nPower of A (each element squared):")
print(power_A)

Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Multiplication:
[[ 5 12]
 [21 32]]

Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Dot Product:
[[19 22]
 [43 50]]

Trigonometric functions:
sin(A):
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]
cos(A):
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]
tan(A):
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]

Sum of all elements in A: 10

Transpose of A:
[[1 3]
 [2 4]]

Power of A (each element squared):
[[ 1  4]
 [ 9 16]]
